# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Ellie's Place"
tagline:          'Just a place'
description:      'A place for Ellie to put her stuff.'
url:              http://eltariel.com
baseurl:          /

author:
  name:           'Ellie Tomkins'
  url:            http://eltariel.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/eltariel
